var jsonSamplesList = [
  {
      "title": "Azure Media Services Overview",
      "src": "//amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "On Demand [Azure Promo]",
      "src": "//amssamples.streaming.mediaservices.windows.net/69fbaeba-8e92-4740-aedc-ce09ae945073/AzurePromo.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "Live (Smooth Ingest) - 24x7",
      "src": "//ampdemolive-usct.streaming.media.azure.net/1f48130b-a059-42ac-9595-501b0824188d/85306180-5146-44e7-91e8-2be2529f7528.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "DRM (PlayReady/Widevine) - On Demand [Big Buck Bunny]",
      "src": "//amssamples.streaming.mediaservices.windows.net/622b189f-ec39-43f2-93a2-201ac4e31ce1/BigBuckBunny.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": true,
      "playreadytoken": "",
      "widevine": true,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "DRM (PlayReady/Widevine) - Live (Smooth Ingest)",
      "src": "//ampdemolive-usct.streaming.media.azure.net/738c6e3a-6d6b-44f2-b143-05b899873317/dd35ec07-0648-46e0-8246-cba4b51777e4.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": true,
      "playreadytoken": "",
      "widevine": true,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "AES (no token) - On Demand [Sintel]",
      "src": "//amssamples.streaming.mediaservices.windows.net/49b57c87-f5f3-48b3-ba22-c55cfdffa9cb/Sintel.ism/manifest",
      "format": "auto",
      "aes": true,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "AES (SWT token) - On Demand [Big Buck Bunny Trailer]",
      "src": "//amssamples.streaming.mediaservices.windows.net/9ead18f1-29f8-453c-8721-4becc00ff611/BigBuckBunnyTrailer.ism/manifest",
      "format": "auto",
      "aes": true,
      "aestoken": "Bearer%3Durn%253amicrosoft%253aazure%253amediaservices%253acontentkeyidentifier%3D5f5076de-4322-42f7-a533-6265f686d5b9%26Audience%3Durn%253atest%26ExpiresOn%3D4581880130%26Issuer%3Dhttp%253a%252f%252ftestacs.com%252f%26HMACSHA256%3D%252bx77Qo0CeBzP4aCntfe2sVkbKeKguOUNAebHQb53sLc%253d",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "AES (JWT token) - On Demand [Tears of Steel Teaser]",
      "src": "//amssamples.streaming.mediaservices.windows.net/830584f8-f0c8-4e41-968b-6538b9380aa5/TearsOfSteelTeaser.ism/manifest",
      "format": "auto",
      "aes": true,
      "aestoken": "Bearer%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI5ZGRhMGJjYy01NmZiLTQxNDMtOWQzMi0zYWI5Y2M2ZWE4MGIiLCJpc3MiOiJodHRwOi8vdGVzdGFjcy5jb20vIiwiYXVkIjoidXJuOnRlc3QiLCJleHAiOjE3MTA4MDczODl9.lJXm5hmkp5ArRIAHqVJGefW2bcTzd91iZphoKDwa6w8",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "AES (no token) - Live (Smooth Ingest)",
      "src": "//ampdemolive-usct.streaming.media.azure.net/bf05ef74-1714-4217-81a9-6c0ae734be64/1a48db6b-16f4-4883-9f03-3e1491b14697.ism/manifest",
      "format": "auto",
      "aes": true,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "PlayReady (static/no token) - On Demand [Tears of Steel Teaser]",
      "src": "//amssamples.streaming.mediaservices.windows.net/de1470b3-7b3c-4902-ab53-d19b37ef3bd7/TearsOfSteelTeaser.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": true,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "PlayReady (dynamic/no token) - On Demand [Sintel Trailer]",
      "src": "//amssamples.streaming.mediaservices.windows.net/bf657309-71d9-4436-b94b-8ac0d2ca222b/SintelTrailer.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": true,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "PlayReady (dynamic/SWT token) - On Demand [Big Buck Bunny]",
      "src": "//amssamples.streaming.mediaservices.windows.net/8b661219-cef3-4413-9471-a0b02794cc4c/BigBuckBunny.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": true,
      "playreadytoken": "Bearer%3Durn%253amicrosoft%253aazure%253amediaservices%253acontentkeyidentifier%3Dea388c3e-a0ec-4117-8564-ae40b31ca416%26Audience%3Durn%253atest%26ExpiresOn%3D4581880646%26Issuer%3Dhttp%253a%252f%252ftestacs.com%252f%26HMACSHA256%3DBk8lBOgQvNyfL5ztAqmud3y652FBTkVPmkG2CQuIup4%253d",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "PlayReady (dynamic/no token) - Live (Smooth Ingest)",
      "src": "//ampdemolive-usct.streaming.media.azure.net/ee87b195-e441-4358-a6de-d188a2ef66f7/99bb8b58-dbb7-4901-9f92-c43648e92837.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": true,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "Subtitles (WebVTT) - On Demand [Tears of Steel]",
      "src": "//amssamples.streaming.mediaservices.windows.net/bc57e088-27ec-44e0-ac20-a85ccbcd50da/TearsOfSteel.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "English,en,//amssamples.streaming.mediaservices.windows.net/bc57e088-27ec-44e0-ac20-a85ccbcd50da/TOS-en.vtt;Spanish,es,//amssamples.streaming.mediaservices.windows.net/bc57e088-27ec-44e0-ac20-a85ccbcd50da/TOS-es.vtt;French,fr,//amssamples.streaming.mediaservices.windows.net/bc57e088-27ec-44e0-ac20-a85ccbcd50da/TOS-fr.vtt;Italian,it,//amssamples.streaming.mediaservices.windows.net/bc57e088-27ec-44e0-ac20-a85ccbcd50da/TOS-it.vtt",
      "poster": ""
  },
  {
      "title": "Dynamic Manifest - On Demand [Elephant's Dream]",
      "src": "//amssamples.streaming.mediaservices.windows.net/b6822ec8-5c2b-4ae0-a851-fd46a78294e9/ElephantsDream.ism/manifest(filtername=FirstFilter)",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "Multi-Audio - On Demand [Elephant's Dream]",
      "src": "//amssamples.streaming.mediaservices.windows.net/55034fb3-11af-43e4-a4de-d1b3ca56c5aa/ElephantsDream_MultiAudio.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "Multi-Audio - On Demand [Sintel]",
      "src": "//amssamples.streaming.mediaservices.windows.net/f1ee994f-fcb8-455f-a15d-07f6f2081a60/Sintel_MultiAudio.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "Dolby Digital Plus - On Demand [Silent]",
      "src": "//amssamples.streaming.mediaservices.windows.net/d499bfae-117a-40ab-9bd4-036cc575fac3/DolbyDigitalPlus.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
  {
      "title": "4K - On Demand [Llama Drama]",
      "src": "//amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "",
      "subtitles": "",
      "poster": ""
  },
    {
        "title": "Progressive MP4 [Azure Promo]",
        "src": "//amssamples.streaming.mediaservices.windows.net/2e91931e-0d29-482b-a42b-9aadc93eb825/AzurePromo.mp4",
        "format": "mp4",
        "aes": false,
        "aestoken": "",
        "playready": false,
        "playreadytoken": "",
        "widevine": false,
        "widevinetoken": "",
        "captions": "",
        "subtitles": "",
        "poster": ""
    },
      {
          "title": "Progressive MP3 [Elephant's Dream]",
          "src": "//amssamples.streaming.mediaservices.windows.net/bddc6db2-3f95-4137-872a-b62a6c19e891/ElephantsDreamAudio.mp3",
          "format": "audio/mp3",
          "aes": false,
          "aestoken": "",
          "playready": false,
          "playreadytoken": "",
          "widevine": false,
          "widevinetoken": "",
          "captions": "",
          "subtitles": "",
          "poster": ""
      },
  {
      "title": "Indexer Demo [Microsoft HoloLens Demo]",
      "src": "//nimbuspm.origin.mediaservices.windows.net/aed33834-ec2d-4788-88b5-a4505b3d032c/Microsoft's HoloLens Live Demonstration.ism/manifest",
      "format": "auto",
      "aes": false,
      "aestoken": "",
      "playready": false,
      "playreadytoken": "",
      "widevine": false,
      "widevinetoken": "",
      "captions": "Indexer,en,http://nimbuspm.origin.mediaservices.windows.net/aed33834-ec2d-4788-88b5-a4505b3d032c/pp4_blog_demo.vtt",
      "subtitles": "",
      "poster": ""
  }
]